---
# defaults file for ide

# Path to bashrc script.
ide_bashrc_config: "{{ ansible_env.HOME }}/.bashrc.d/ide"
# Path to directory with Nvim settings.
ide_nvim_dir: "{{ ansible_env.HOME }}/.config/nvim"

# List of required RPM packages.
ide_packages:
  - neovim
  - bat # Replace cat/less in telescope.nvim.
  - fd-find # Speedup find in telescope.nvim.
  - ripgrep # Speedup grep in telescope.nvim.
  - lazygit # Git UI and integration with Neovim.
  - cargo # Build ruff for python in mason.nvim.

# List of enabled language plugins.
ide_lang:
  - ansible
  - docker
  - go
  - json
  - markdown
  - python
  - shell
  - typescript
  - toml
  - yaml
