---
# defaults file for backup

backup_workaround: true # fix for https://github.com/zocker-160/SyncThingy/issues/6
backup_portal_config: "{{ ansible_env.HOME }}/.config/xdg-desktop-portal/sway-portals.conf"

backup_flatpak_packages:
  - com.github.zocker_160.SyncThingy
