---
# playbook for deploy roles

- name: Collection
  hosts: localhost
  connection: local
  tasks:
    - name: Deploy Window manager
      ansible.builtin.import_role:
        name: voler88.workstation.wm

    - name: Deploy Terminal emulator
      ansible.builtin.import_role:
        name: voler88.workstation.term

    - name: Deploy Backup tools
      ansible.builtin.import_role:
        name: voler88.workstation.backup

    - name: Deploy IDE
      ansible.builtin.import_role:
        name: voler88.workstation.ide
